# Generated by Django 5.2.5 on 2025-08-29 15:07

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogauthormodel',
            options={'verbose_name': 'Blog author', 'verbose_name_plural': 'Blog authors'},
        ),
        migrations.AlterModelOptions(
            name='blogcategorymodel',
            options={'verbose_name': 'Blog category', 'verbose_name_plural': 'Blog categories'},
        ),
        migrations.AlterModelOptions(
            name='blogtagmodel',
            options={'verbose_name': 'Blog tag', 'verbose_name_plural': 'Blog tags'},
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
