# Generated by Django 5.2.5 on 2025-08-29 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blogauthormodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogViewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_ip', models.CharField(max_length=15)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='blogs.blogmodel')),
            ],
            options={
                'verbose_name': 'Blog view',
                'verbose_name_plural': 'Blog views',
            },
        ),
    ]
